language: cpp

compiler:
  - gcc
  - clang

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - sudo apt-get update -qq

install:
  - >
   sudo apt-get install -qq ruby-full rake gperf pkg-config bison libglew-dev
   freeglut3-dev gettext libpng12-dev libsdl-ttf2.0-dev
   libsdl-mixer1.2-dev libsdl-image1.2-dev libpcre3-dev libxml++2.6-dev
   libfreetype6-dev libdevil-dev libboost1.55-all-dev

script:
  - mkdir tsc/build && cd tsc/build && cmake .. && make && sudo make install
